version: '3'

services:
  mcp-bedrock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7002:7002"  # MCP Service API
      - "8502:8502"  # ChatBot UI
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - LOG_DIR=./logs
      - CHATBOT_SERVICE_PORT=8502
      - MCP_SERVICE_HOST=127.0.0.1
      - MCP_SERVICE_PORT=7002
      - API_KEY=${API_KEY:-123456}
      - MAX_TURNS=100
    volumes:
      - ./logs:/app/logs
      - ./conf:/app/conf
      - ./tmp:/app/tmp
    restart: unless-stopped
